HANAHANA_CM_ver4/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hana_cm/', include('hana_cm.urls')),
    path('', RedirectView.as_view(url='/hana_cm/')), 
]

hana_cm/urls.py
from django.urls import path
from . import views

app_name = 'hana_cm'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/',views.DetailView.as_view(), name='detail'),
    path('create/', views.CreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.UpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteView.as_view(), name='delete'),
    path('k_create/', views.youkaigo_create.as_view(), name='kcreate'),
    path('k_detail/<int:pk>/',views.youkaigo_DetailView.as_view(), name='kdetail'),
    path('k_update/<int:pk>/', views.youkaigo_UpdateView.as_view(), name='kupdate'),
    path('youkaigodo/', views.Youkaigodo_IndexView.as_view(), name='youkaigodo'),
    path('k_delete/<int:pk>/', views.Youkaigodo_DeleteView.as_view(), name='kdelete'),
]

hana_cm/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django import forms


# Create your models here.
#利用者クラス
class Riyousha(models.Model):
    hihoken_no = models.BigIntegerField()
    name = models.CharField(max_length=50)
    name_kana = models.CharField(max_length=100)
    nyuuryoku_date = models.DateField(auto_now_add=False)
    sex = models.BooleanField()
    pub_date = models.DateTimeField(auto_now_add=True)
    #slug = models.SlugField(max_length=20, blank=True, null=True)
    

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('hana_cm:detail', kwargs={'pk': self.pk})

class YouKaigoDo(models.Model):
    riyousha = models.ForeignKey('Riyousha', on_delete=models.CASCADE,\
        related_name='Youkaigodo_riyousha')
    
    youkaigodo_nyuuryokuDate = models.DateField(auto_now_add=False)
    kaigodo = models.ForeignKey('Kaigodo', on_delete=models.PROTECT, db_column='kaigodo')
    nintei_date = models.DateField(auto_now_add=False)
    start_date = models.DateField(auto_now_add=False)
    end_date = models.DateField(auto_now_add=False)
    pub_date = models.DateTimeField(auto_now_add=True)
    

    class Meta:
        constraints = [
            # 先生-レッスン実施日のペアでユニーク制約
            models.UniqueConstraint(
                fields=["riyousha", "youkaigodo_nyuuryokuDate"],
                name="riyousha_date_unique"
            )
        ]

    def get_absolute_url(self):
        return reverse('hana_cm:kdetail', kwargs={'pk': self.pk}) 

''' class NyuuryokuDate(models.Model):
    riyousha = models.ForeignKey('Riyousha', on_delete=models.CASCADE,\
        related_name='nyuuryoku_riyousha')
    nyuuryoku_date = models.DateField(auto_now_add= False) '''

''' class Youkaigodo_NyuuryokuDate(models.Model):
    riyousha = models.ForeignKey('Riyousha', on_delete=models.CASCADE,\
        related_name='youkaigodo_nyuuryoku_riyousha')
    nyuuryoku_date = models.DateField(auto_now_add= False) '''

class Adress(models.Model):
    riyousha = models.ForeignKey('Riyousha', on_delete=models.CASCADE,\
        related_name='adress_riyousha')
    post_no = models.CharField(max_length=8,)
    adress = models.CharField(max_length=100)
    pub_date = models.DateTimeField(auto_now_add=True)

class CareManager(models.Model):
    riyousha=models.ForeignKey('Riyousha', on_delete=models.CASCADE,\
        related_name='cm_riyousha')
    cm_name=models.CharField(max_length=50)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.cm_name



class Kaigodo(models.Model):
    ''' riyousha = models.ForeignKey('Riyousha', on_delete=models.CASCADE,\
        related_name='kaigodo_riyousha') '''
    kaigodo = models.CharField(max_length=4)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.kaigodo

class Riyousha_kihon(models.Model):
    riyousha = models.ForeignKey('Riyousha', on_delete=models.CASCADE)
    adress = models.ForeignKey('Adress', on_delete=models.CASCADE)
    caremanager = models.ForeignKey('CareManager', on_delete=models.CASCADE)

class Adl_1(models.Model):
    IS_USED_CHOICES = (
        (False, 'なし'),
        (True, 'あり'),
    )
    riyousha = models.ForeignKey('Riyousha', on_delete=models.CASCADE)
    nyuuryoku_date = models.DateField(auto_now_add=False)
    non = models.BooleanField( help_text="「なし」なら、チェックしてください",)
    left_upper_limbs = models.BooleanField( choices=IS_USED_CHOICES,help_text="「左上肢に麻痺」があれば、チェックしてください")
    left_lower_limbs = models.BooleanField( choices=IS_USED_CHOICES,help_text="「左下肢に麻痺」があれば、チェックしてください")
    right_upper_limbs = models.BooleanField( choices=IS_USED_CHOICES,help_text="「右上肢に麻痺」があれば、チェックしてください")
    right_lower_limbs = models.BooleanField( choices=IS_USED_CHOICES,help_text="「右下肢に麻痺」があれば、チェックしてください")
    others = models.BooleanField( help_text="「その他」があれば、チェックしてください。詳細を「麻痺その他」に記入してください")
    paralysis_others = models.CharField(max_length=50)
    pub_date = models.DateTimeField('date published',auto_now_add=True)

hana_cm/forms.py
from django import forms
from .models import YouKaigoDo,Riyousha
#from bootstrap_datepicker_plus import DatePickerInput

''' class YoykaigoDoForm(forms.ModelForm):
    
    class Meta:
        model = YouKaigoDo
        fields = ['riyousha', 'youkaigodo_nyuuryokuDate', 'nintei_date',
        ]
 '''
class FindForm(forms.Form):
    find = forms.CharField(max_length=255, label='利用者名',required=False,\
        widget=forms.TextInput(attrs = {'class':'form-controle'})) 


class CreateForm(forms.ModelForm):
    
    class Meta:
        model = Riyousha
        ''' widgets = {'nyuuryoku_date':DatePickerInput(format='%y-%m-%d')
        } '''
        
        fields = ('hihoken_no','name','name_kana','nyuuryoku_date','sex')
        labels = {
            'hihoken_no':'被保険者番号',
            'name':'氏名',
            'name_kana':'氏名カナ',
            'nyuuryoku_date':'入力日',
            'sex':'性別',
        }

class UpdateForm(forms.ModelForm):
    
    class Meta:
        model = Riyousha
        ''' widgets = {'nyuuryoku_date':DatePickerInput(format='%y-%m-%d')
        } '''
        
        fields = ('hihoken_no','name','name_kana','nyuuryoku_date','sex')
        labels = {
            'hihoken_no':'被保険者番号',
            'name':'氏名',
            'name_kana':'氏名カナ',
            'nyuuryoku_date':'入力日',
            'sex':'性別',
        }
         

        

hana_cm/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from .models import Riyousha,YouKaigoDo
from django.shortcuts import redirect
from django.contrib.admin.widgets import AdminDateWidget
from django.shortcuts import render, get_object_or_404
from django.views import View
from .forms import CreateForm,UpdateForm
#from django.forms import FindForm

# Create your views here.
class IndexView(generic.ListView):
    model = Riyousha

class DetailView(generic.DetailView):
    model = Riyousha
    

class CreateView(generic.edit.CreateView):
    model = Riyousha
    #fields = '__all__'
    form_class = CreateForm
    model = Riyousha
    

class Riyousha_CreateView(generic.edit.CreateView):
    model = Riyousha
    fields = '__all__'

class UpdateView(generic.edit.UpdateView):
    model = Riyousha
    form_class = UpdateForm
    model = Riyousha
    success_url = reverse_lazy('hana_cm:index')

class DeleteView(generic.edit.DeleteView):
    model = Riyousha
    success_url = reverse_lazy('hana_cm:index')

''' class DetailView(generic.DetailView):
    model = Riyousha '''

class youkaigo_create(generic.edit.CreateView):
    model = YouKaigoDo
    fields = '__all__'
    ''' widgets = {
            'date_field': AdminDateWidget(),
    } '''

class youkaigo_UpdateView(generic.edit.UpdateView):
    model = YouKaigoDo
    fields = '__all__'
    success_url = reverse_lazy('hana_cm:youkaigodo')

''' class youkaigo_update(generic.edit.UpdateView):
    model = YouKaigoDo
    fields = '__all__'  '''

class youkaigo_DetailView(generic.DetailView):
    model = YouKaigoDo

class Find(View):

    def __init__(self):
        self.context = {
            'title': "要介護認定",
            'message':'認定状況',
            'form':FindForm()
        }

    def get(self,request):
        return render(request, 'hana_cm/find.html', self.context)

    def post(self,request):
        self.context['form'] = FindForm(request.POST)
        return render(request, 'hana_cm/find.html', self.context)

class Youkaigodo_IndexView(generic.ListView):
    model = YouKaigoDo

class Youkaigodo_DeleteView(generic.edit.DeleteView):
    model = YouKaigoDo
    success_url = reverse_lazy('hana_cm:youkaigodo')

hana_cm/templates/hana_cm/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'>
        <meta name='viewport' content='width=device-width, initiai-scake=1,shrink-to-fit=no'>
        <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css'integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
       <style>body{padding-top:80px;}</style> 
       <title>アセスメント表</title>
    </head>
    
        
         
        <nav class="navbar navbar-expand-lg navbar-dark bg-success fixed-top  ">
            <a class="navbar-brand" href="{% url "hana_cm:index" %}">アセスメント表</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="navbar-brand" href="{% url "hana_cm:youkaigodo" %}">認定情報 {% comment %} <span class="sr-only">(current)</span> {% endcomment %}</a>
                  </li>
                {% comment %} 
                <li class="nav-item">
                  <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Dropdown
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                  </div>
                </li>
                <li class="nav-item">
                  <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li>
              </ul>
              <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
              </form> {% endcomment %}
            </div> 
          </nav>

            
        {% comment %}
           <nav class='navbar navbar-extend-lg navbar-dark bg-success  fixed-top '> 
         <body>    
            <a class="navbar-brand" href='{% url "hana_cm:index" %}'>アセスメント表</a>
            <button class="navbar-toggler" type="button"  data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"  area-expanded="false" area-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span> 
            </button>       
                {% comment %} <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                     
                     
                
                        
                <div class="collapse navbar-collapse" id="navbarSupportedContent" > 
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item "><a class="nav-link" href='{% url "hana_cm:index" %}'>アセスメント表<span class="sr-only">(current)</span></a></li> 
                        <li class -"nav-item"><a class="nav-link" href='{% url "hana_cm:youkaigodo" %}'>認定情報</a></li>
                    
                    </ul>
                <form class="form-control mr-sm-2" type="search" placeholder='Search' area-label='Search'></form>
                </div>
            </div>
        </nav> 
            <ul class = "navibar-nav">
                <li class="nav-item activ">
                <a class='nav-link active' href='{% url "hana_cm:index" %}'>アセスメント表</span></a></li> 
                <li class="nav-item">
                <a class='navbar-brand' href='{% url "hana_cm:youkaigodo" %}'>認定情報</a></li>
                </div>

                
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav4" aria-controls="navbarNav4" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand" href='{% url "hana_cm:index" %}'>Navbar</a>
                <div class="collapse navbar-collapse">
                <ul class="navbar-nav">
                <li class="nav-item active">
                <a class="nav-link" href='{% url "hana_cm:index" %}'>新規登録</a> <nav class='navbar navbar-extend-lg navbar-dark bg-success  fixed-top '> 
                    <body>    
                       <a class="navbar-brand" href='{% url "hana_cm:index" %}'>アセスメント表</a>
                       <button class="navbar-toggler" type="button"  data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"  area-expanded="false" area-label="Toggle navigation">
                           <span class="navbar-toggler-icon"></span> 
                       </button>       
                           {% comment %} <span class="sr-only">Toggle navigation</span>
                                   <span class="icon-bar"></span>
                                   <span class="icon-bar"></span>
                                   <span class="icon-bar"></span> 
                                
                                
                           
                                   
                           <div class="collapse navbar-collapse" id="navbarSupportedContent" > 
                               <ul class="navbar-nav mr-auto">
                                   <li class="nav-item "><a class="nav-link" href='{% url "hana_cm:index" %}'>アセスメント表<span class="sr-only">(current)</span></a></li> 
                                   <li class -"nav-item"><a class="nav-link" href='{% url "hana_cm:youkaigodo" %}'>認定情報</a></li>
                               
                               </ul>
                           <form class="form-control mr-sm-2" type="search" placeholder='Search' area-label='Search'></form>
                           </div>
                       </div>
                   </nav> {% endcomment %}
                
        
        <div class='container'>
            {% block content %}  
            {% endblock %}
        </div>
    </nav>
    </body>
</html>

hana_cm/templates/hana_cm/riyousha_confirm_delete.html
{% extends './base.html' %}
{% block content %}
    <h1>利用者の削除</h1>

        <p>{{riyousha.name}}様を削除しますか？</p>
        <form action='' method='post'>{% csrf_token %}
            <button type='submit' class='submit delete'>削除する</button>
        </form>

        <div>
            <p><a href='JavaScript:history.back()'>&lt; 戻る</a></p>
        </div>

{% endblock %} 

hana_cm/templates/hana_cm/riyousha_detail.html
{% extends './base.html' %}
{% block content %}
    <h1>氏名　{{ riyousha.name }}</h1>

        <p>被保険者番号：　　{{riyousha.hihoken_no}}</p>
        <p>カナ　　　　：　　{{riyousha.name_kana}}</p>
        <p>性別　　　　:  　　{% if riyousha.sex == False %}女性{% endif %}
                         　　{% if riyousha.sex == True %}男性{% endif %}</p>
        <p>入力日　　　：　　{{riyousha.nyuuryoku_date}}</p>

        <div>
            <a href='{% url "hana_cm:index" %}'><button class="py-o">一覧</button></a> |
            <a href='{% url "hana_cm:update" riyousha.pk %}'><button class="py-o">編集</button></a> |
            <a href='{% url "hana_cm:delete" riyousha.pk %}'><button class="py-o">削除</button></a> | 
            <a href='{% url "hana_cm:youkaigodo"  %}'><button class="py-o">認定情報</button></a> | 
        </div>
        <div>
            
           {% comment %}  <a href='{% url "hana_cm:update" riyousha.pk %}'>編集</a> |
            <a href='{% url "hana_cm:delete" riyousha.pk %}'>削除</a> |    {% endcomment %} 
        </div>
        <div>
            {% comment %} <a href='{% url "hana_cm:riyousha_create" %}'>利用者の追加</a>  {% endcomment %} 
        </div> 
        <div>
            <a href='JavaScript:history.back()'>&lt;戻る</a>
        </div>     
{% endblock %} 

hana_cm/templates/hana_cm/riyousha_form.html
{% extends './base.html' %}
{% block content %}
<h1>利用者情報の{{ object|yesno:'更新,作成' }}</h1>

<form action='' method='post'>
    {% csrf_token %}
    {{form.as_p}}
    <button type='submit' class='submit'>{{object|yesno:'更新,作成'}}</button>  
</form> 
<div>
    <a href='JavaScript:history.back()'>&lt;戻る</a>
</div>     
{% endblock %} 

hana_cm/templates/hana_cm/riyousha_list.html
{% extends './base.html' %}
{% block content %}
<h1>利用者一覧</h1>
<table class='table table-striped table-hover'>
    <tr>
        <th>被保険者番号</th><th>氏名</th><th>性別</th><th>入力日</th>
    </tr>



    {% for riyousha in object_list %}
             
    <tr>
        <td>{{riyousha.hihoken_no}}</td>
        <td><a href ='{% url "hana_cm:detail" riyousha.pk %}'>{{riyousha.name}}</a></td>  
        <td>{% if riyousha.sex == False %}女性{% endif %}
            {% if riyousha.sex == True %}男性{% endif %}
        </td>
        <td>{{riyousha.nyuuryoku_date}}</td>     
    </tr> 
       
        
    {% endfor %} 
</table>
    <div>
        <a href='{% url "hana_cm:create" %}'><button class="py-o">利用者の追加</button></a>
        <a href='{% url "hana_cm:youkaigodo" %}'><button class="py-o">要介護認定</button></a>    
    </div> 

    {% comment %} <a href='{% url "hana_cm:kcreate" youkaigodo.pk %}'>認定情報</a> |  {% endcomment %}
    <div>
        <a href='JavaScript:history.back()'>&lt;戻る</a>
    </div>     
{% endblock %} 

hana_cm/templates/hana_cm/youkaigodo_confirm_delete.html
{% extends './base.html' %}
{% block content %}
    <h1>要介護情報の削除</h1>
    <h1>{{ youkaigodo.riyousha.name }}様</h1>

    {% comment %} {% for youkaigodo in object_list %} {% endcomment %}
        <p>入力日　　　：　{{youkaigodo.youkaigodo_nyuuryokuDate}}</p> 
        <p>認定日　　　：　{{youkaigodo.nintei_date}}</p>
        
        <p>認定開始日　:　　{{youkaigodo.start_date}}{% comment %} <span class="datetimeshortcuts">&nbsp;<a href="#">Today</a>&nbsp;|&nbsp;<a href="#" id="calendarlink1"><span class="date-icon" title="Choose a Date"></span></a></span></p> {% endcomment %}
        <p>認定終了日　：　{{youkaigodo.end_date}}</p>
        <p>要介護度　　：　{{youkaigodo.kaigodo}}</p>
        <h2>の認定情報を削除しますか？</h2>
        <form action='' method='post'>{% csrf_token %}
            <button type='submit' class='submit delete'>削除する</button>
        </form>

        <div>
            <p><a href='JavaScript:history.back()'>&lt; 戻る</a></p>
        </div>

{% endblock %} 

hana_cm/templates/hana_cm/youkaigodo_detail.html
{% extends './base.html' %}
{% block content %}
    <h1>{{ youkaigodo.riyousha.name }}</h1>

    {% comment %} {% for youkaigodo in object_list %} {% endcomment %}
        <p>入力日　　　：　{{youkaigodo.youkaigodo_nyuuryokuDate}}</p> 
        <p>認定日　　　：　{{youkaigodo.nintei_date}}</p>
        
        <p>認定開始日　:　　{{youkaigodo.start_date}}{% comment %} <span class="datetimeshortcuts">&nbsp;<a href="#">Today</a>&nbsp;|&nbsp;<a href="#" id="calendarlink1"><span class="date-icon" title="Choose a Date"></span></a></span></p> {% endcomment %}
        <p>認定終了日　：　{{youkaigodo.end_date}}</p>
        <p>要介護度　　：　{{youkaigodo.kaigodo}}</p>

        <div>
            <a href='{% url "hana_cm:index" %}'><button class="py-o">一覧</button></a> |
            <a href='{% url "hana_cm:kupdate" youkaigodo.id %}'><button class="py-o">変更後、上書き保存</button></a> |
            <a href='{% url "hana_cm:kcreate"  %}'><button class="py-o">要介護認定の追加</button></a> |  
            <a href='{% url "hana_cm:kdelete" youkaigodo.id %}'><button class="py-o">削除</button></a> |  
        </div>
        
        <div>
             <a href='{% url "hana_cm:kcreate" %}'>利用者の追加</a>  
        </div> 
        
        <div>
            <a href='JavaScript:history.back()'>&lt;戻る</a>
        </div>     
{% endblock %} 

hana_cm/templates/hana_cm/youkaigodo_form.html
{% extends './base.html' %}
{% block content %}
<h1>要介護認定の{{ object|yesno:'変更後、上書き保存,作成'}}</h1>

<form action='' method='post'>{% csrf_token %}
    {{ form.as_p }}
    
    <button type='submit' class='submit'>{{ object|yesno:'変更後、上書き保存,作成'}}</button>
</form>
<div>
    <a href='JavaScript:history.back()'>&lt; 戻る</a>
</div>
        

{% endblock %} 

hana_cm/templates/hana_cm/youkaigodo_list.html
{% extends './base.html' %}
{% block content %}
<h1>要介護認定情報の一覧</h1>
<table class='table table-striped table-hover'>
    <tr>
        <th>利用者名</th><th>要介護度</th><th>開始日</th><th>終了日</th><th>認定日</th>
    </tr>



    {% for youkaigodo in object_list %}
             
    <tr>
        <td><a href ='{% url "hana_cm:kdetail" youkaigodo.id %}'>{{youkaigodo.riyousha.name}}</a></td> 
        <td>{{youkaigodo.kaigodo}}</td>
        <td>{{youkaigodo.start_date}}</td>
        <td>{{youkaigodo.end_date}}</td> 
        <td>{{youkaigodo.nintei_date}}</td> 
        {% comment %} <td>{{riyousha.sex}}</td>
        <td>{{riyousha.nyuuryoku_date}}</td>  {% endcomment %}    
    </tr> 
       
        
    {% endfor %} 
</table>
    <div>
        <a href='{% url "hana_cm:create" %}'><button class="py-o">利用者の追加</button></a> 
        <a href='{% url "hana_cm:kcreate" %}'><button class="py-o">要介護認定の追加</button></a> 
    </div> 

    {% comment %} <a href='{% url "hana_cm:kdetail" riyousha.pk %}'>認定情報</a> | {% endcomment %} 
    <div>
        <a href='JavaScript:history.back()'>&lt;戻る</a>
    </div>     
{% endblock %} 